spring:
  datasource:
    username: root
    password: root

google:
  drive:
    credentials-path: classpath:credentials.json
    folder-id: tu_folder_id_de_drive

musescore:
  path: C:/Program Files/MuseScore 4/bin/MuseScore4.exe