spring:
  application:
    name: anthology
  
  datasource:
   # url: jdbc:mysql://localhost:3306/anthologyDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    #UTN CONNECTION
    url: jdbc:mysql://172.16.1.64:3306/AnthologyTest
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bdd1
    password: bdd1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  profiles:
    active: local

  server:
    port: 8080

    # Sitio de generacion de secret-key (https://jwtsecrets.com/)
    # 15 minutos de validacion
    security:
      jwt:
        secret-key: 451cd6fdf7cb8eeb5e91d8c1ef9d5261f76e50c61451e56c05de53540d153b3862124270c9a40424ce6d82ef115cb4c08952ffad3cacaa6f2206159b00ff2a50
        expiration-ms: 900000