spring:
  application:
    name: anthology
  
  datasource:
   # url: jdbc:mysql://localhost:3306/anthologyDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    #UTN CONNECTION
    url: jdbc:mysql://172.16.1.64:3306/AnthologyTest
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bdd1
    password: bdd1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  profiles:
    active: local

  server:
    port: 8080